// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArAUqIjTUuDylxmFaN38nIk3TCPfj8Tqs',
    appId: '1:75100525802:web:013e377af0ecd4e78f3393',
    messagingSenderId: '75100525802',
    projectId: 'pay-65',
    authDomain: 'pay-65.firebaseapp.com',
    storageBucket: 'pay-65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH6oqm_xGIWkrYE3UtZO9mdyRhrTg43zQ',
    appId: '1:75100525802:android:e92f4a1472378cba8f3393',
    messagingSenderId: '75100525802',
    projectId: 'pay-65',
    storageBucket: 'pay-65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4_hrV6REc1TcKnPpqKHNE05_2CDXX3_s',
    appId: '1:75100525802:ios:59c486f51b238e1a8f3393',
    messagingSenderId: '75100525802',
    projectId: 'pay-65',
    storageBucket: 'pay-65.firebasestorage.app',
    iosBundleId: 'com.example.payGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4_hrV6REc1TcKnPpqKHNE05_2CDXX3_s',
    appId: '1:75100525802:ios:59c486f51b238e1a8f3393',
    messagingSenderId: '75100525802',
    projectId: 'pay-65',
    storageBucket: 'pay-65.firebasestorage.app',
    iosBundleId: 'com.example.payGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArAUqIjTUuDylxmFaN38nIk3TCPfj8Tqs',
    appId: '1:75100525802:web:4916bc615dd0f7eb8f3393',
    messagingSenderId: '75100525802',
    projectId: 'pay-65',
    authDomain: 'pay-65.firebaseapp.com',
    storageBucket: 'pay-65.firebasestorage.app',
  );
}
